### PR TITLE
bonjour: browse all ip versions for mobdev2

### PR DESCRIPTION
**Pull request by doronz88**

### CODE REVIEW

**Comment by nanoscopic** [comment]
What is the need for this? Is this specifically for devices being used wirelessly on ipv4 only networks?

**Comment by doronz88** [comment]
actually its a fix for finding devices that only have ipv6 addresses over mobdev2. previously we only filtered out the ipv4 addresses

**Comment by nanoscopic** [comment]
Thanks. Was wondering as I hadn't seen an instance where ipv4 was useful for this.

You might consider using mdns requests more directly aimed at the interfaces directly rather than using zeroconf. Zeroconf is huge and slow.

**Comment by doronz88** [comment]
Zeroconf was never the first choice, but it performs the required job. If you feel up to the task of implementing a better standalone mdns queries, PRs are more then welcome 😃

**Pull request merged**
