### PR TITLE
usbmux: tell usbmuxd responses format by the msgtype (#346)

### PR DESCRIPTION
**Pull request by doronz88**
usbmuxd2 is informing wrong version with response packets

### CODE REVIEW

**Review by gershom-mx — COMMENTED** [review]
I appear to be getting the same error:
```
raise MuxException(f'Invalid packet type received: {response}')
pymobiledevice3.exceptions.MuxException: Invalid packet type received: Container: 
    header = Container: 
        version = (enum) BINARY 0
        message = (enum) PLIST 8
        tag = 0
    data = b'<?xml version="1'... (truncated, total 840)
```

**Comment by doronz88** [comment]
Can you give a full backtrace to verify it's the same?
Also, are you sure you are running the PR version? Because it seems like `pymobiledevice3` still thinks `usbmuxd2` is talking in the protocol it said it would (The binary one) and therefore uses the `BinaryMuxConnection` instead of `PlistMuxConnection`

**Comment by gershom-mx** [comment]
```
File "<stdin>", line 1, in <module>
  File "/home/x/.local/lib/python3.10/site-packages/pymobiledevice3/lockdown.py", line 126, in __init__
    self.service = ServiceConnection.create(self.medium, self.identifier, self.SERVICE_PORT,
  File "/home/x/.local/lib/python3.10/site-packages/pymobiledevice3/service_connection.py", line 104, in create
    return ServiceConnection.create_using_usbmux(identifier, port, connection_type=connection_type)
  File "/home/x/.local/lib/python3.10/site-packages/pymobiledevice3/service_connection.py", line 87, in create_using_usbmux
    target_device = select_device(udid, connection_type=connection_type)
  File "/home/x/.local/lib/python3.10/site-packages/pymobiledevice3/usbmux.py", line 379, in select_device
    for device in list_devices():
  File "/home/x/.local/lib/python3.10/site-packages/pymobiledevice3/usbmux.py", line 367, in list_devices
    mux.get_device_list(0.1)
  File "/home/x/.local/lib/python3.10/site-packages/pymobiledevice3/usbmux.py", line 225, in get_device_list
    self._receive_device_state_update()
  File "/home/x/.local/lib/python3.10/site-packages/pymobiledevice3/usbmux.py", line 291, in _receive_device_state_update
    raise MuxException(f'Invalid packet type received: {response}')
pymobiledevice3.exceptions.MuxException: Invalid packet type received: Container: 
    header = Container: 
        version = (enum) BINARY 0
        message = (enum) PLIST 8
        tag = 0
    data = b'<?xml version="1'... (truncated, total 840)

```
I believe I am using the PR, here is code from relevant section in usbmux.py:

```
 # if we sent a bad request, we should re-create the socket in the correct version this time
        sock.close()
        sock = MuxConnection.create_usbmux_socket()

        if response.header.message != usbmuxd_msgtype.PLIST:
            return BinaryMuxConnection(sock)
        else:
            return PlistMuxConnection(sock)
```

**Comment by gershom-mx** [comment]
Maybe this helps? If I change code to only return Plist, it works! 

```
# if we sent a bad request, we should re-create the socket in the correct version this time
        sock.close()
        sock = MuxConnection.create_usbmux_socket()

        if response.header.message != usbmuxd_msgtype.PLIST:
            return PlistMuxConnection(sock)
        else:
            return PlistMuxConnection(sock)

```

**Comment by doronz88** [comment]
I know the expected protocol for usbmuxd2 is a plist, but usbmuxd will use binary and we want to support all variants.

Can you print the returned packet? The one we use to tell the protocol to use

**Comment by gershom-mx** [comment]
Is this the correct data needed?

```
Container: 
    header = Container: 
        version = (enum) BINARY 0
        message = (enum) RESULT 1
        tag = 1
    data = Container: 
        result = (enum) OK 0
Container: 
    header = Container: 
        version = (enum) BINARY 0
        message = (enum) RESULT 1
        tag = 1
    data = Container: 
        result = (enum) OK 0
```

**Pull request closed without merging**
