### PR TITLE
usbmux: use msgtype to get correct protocol (#346)

### PR DESCRIPTION
**Pull request by doronz88**

### CODE REVIEW

**Review by gershom-mx — COMMENTED** [review]
Something is not working. When I try to run any pymobildedevice3 service, it just hangs with the cursor blinking and no errors.

However, when I remove these edits, and go back to forcing usbmux.py to return PlistMuxConnection(sock), it works right away.

Even if I force usbmux.py tp return PlistMuxConnection(sock) as above, and include edits from 348, it still just hangs.

**Comment by doronz88** [comment]
@johnfgoodman can you recheck with the latest commit? I think the problem is `usbmuxd2` is waiting to get a full plist message. If so - that should fix it.

**Comment by gershom-mx** [comment]
> @johnfgoodman can you recheck with the latest commit? I think the problem is `usbmuxd2` is waiting to get a full plist message. If so - that should fix it.

It now works! Thank you!

**Review by gershom-mx — APPROVED** [review]
Usbmuxd2 works with these changes.

**Comment by doronz88** [comment]
@johnfgoodman Thanks for the huge cooperation. I'll test it for a few more days on a more platforms different configurations and if all goes well I'll merge it. For now it seems like it works on at least most cells in the matrix (windows, macOS, usbfluxd and usbmuxd. still need to test it on Linux & normal usbmuxd).

**Pull request merged**
