### PR TITLE
amfi: handle developer-mode enable errors (#301)

### PR DESCRIPTION
**Pull request by doronz88**

### CODE REVIEW

**Comment by truonggiang0710** [comment]
the log is below
python3 -m pymobiledevice3 amfi enable-developer-mode
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/MAC/Desktop/pymobiledevice3-master/pymobiledevice3/__main__.py", line 78, in <module>
    cli()
  File "/Users/MAC/Desktop/pymobiledevice3-master/pymobiledevice3/__main__.py", line 54, in cli
    cli_commands()
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/MAC/Desktop/pymobiledevice3-master/pymobiledevice3/cli/amfi.py", line 26, in enable_developer_mode
    AmfiService(lockdown).enable_developer_mode()
  File "/Users/MAC/Desktop/pymobiledevice3-master/pymobiledevice3/services/amfi.py", line 59, in enable_developer_mode
    self.enable_developer_mode_post_restart()
  File "/Users/MAC/Desktop/pymobiledevice3-master/pymobiledevice3/services/amfi.py", line 66, in enable_developer_mode_post_restart
    if not resp['success']:
KeyError: 'success'

**Comment by doronz88** [comment]
@truonggiang0710 please verify current branch. You'll have to install with `-e`

**Comment by truonggiang0710** [comment]
@doronz88 I reinstalled by python3 -m pip install -U -e . The log is same as before.
I ran my iPhone 8 Plus with devmodectl command on macOS 13 beta 5. It's unsuccessfully.
So I think the reason is "My iPhone 8 Plus in hello screen".
I summary which ran by "devmodectl streaming" command from Apple
- iPhone 8 Plus at Hello screen => Fail 10/10. Pass 0/10.
- iPhone X at Hello screen => Fail 2/10. Pass 8/10.
The result of pymobiledevice3 is same.

**Comment by doronz88** [comment]
@truonggiang0710 as you can see in here:
https://github.com/doronz88/pymobiledevice3/blob/bugfix/handle_developer_mode_enable_errors/pymobiledevice3/services/amfi.py#L66

Your stack trace doesn't fit this branch version. When installing locally instead, you must first uninstall the previous version (or it will still use the `site-packages` version instead).

```shell
python3 -m pip uninstall pymobiledevice3
python3 -m pip install -e .
```

**Comment by truonggiang0710** [comment]
@doronz88 I did as your recommended. The log is below.
python3 -m pymobiledevice3 amfi enable-developer-mode
2022-08-26 07:24:21 mac __main__[44088] ERROR Failed to enable developer-mode. Device replied with: enable_developer_mode_post_restart() failed: {'Error': 'An unknown error has occured'}

**Review by jaihoonB — COMMENTED** [review]
How to do it

**Comment by doronz88** [comment]
@jaihoonB how to do what? create an issue or discussion with what you are requesting

**Pull request merged**
