### PR TITLE
Move AfcShell to cli/afc.py for PyInstaller no-console support.

### PR DESCRIPTION
**Pull request by Starwarsfan2099**
Building a GUI application using PyInstaller and the `noconsole` option causes errors after importing `pymobiledevice3.services.afc`. The error `AttributeError: 'NoneType' object has no attribute 'isatty'` originates from importing `Cmd2ArgumentParser` without a console on some recent Python versions.

The fix I've done here simply moves `AfcShell` and requirements to `cli/afc.py`. This allows `pymobiledevice3.services.afc` to be imported and `AfcService` to be used in applications without a console. This also keeps the CLI and shell utilities in the same place without importing `Cmd`, `Cmd2ArgumentParser` in the `services.afc` module when they may not be needed.

### CODE REVIEW

**Comment by matan1008** [comment]
Could you please supply the full traceback and a small, reproducible example?

**Comment by doronz88** [comment]
@Starwarsfan2099 this also broke `afc shell`
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/doron/dev/pymobiledevice3/pymobiledevice3/__main__.py", line 11, in <module>
    from pymobiledevice3.cli.apps import cli as apps_cli
  File "/Users/doron/dev/pymobiledevice3/pymobiledevice3/cli/apps.py", line 5, in <module>
    from pymobiledevice3.services.house_arrest import HouseArrestService
  File "/Users/doron/dev/pymobiledevice3/pymobiledevice3/services/house_arrest.py", line 4, in <module>
    from pymobiledevice3.services.afc import AfcService, AfcShell
ImportError: cannot import name 'AfcShell' from 'pymobiledevice3.services.afc' (/Users/doron/dev/pymobiledevice3/pymobiledevice3/services/afc.py)
```

**Comment by Starwarsfan2099** [comment]
@matan1008 Of course.
```
# test.py
from pymobiledevice3.services.afc import AfcService
from tkinter import *

root = Tk()
a = Label(root, text ="Hello World")
a.pack()
root.mainloop()
```

On Windows, build with `pyinstaller -F --distpath . --noconsole test.py`. When running `test.exe`, the following error is produced:

```
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    from pymobiledevice3.services.afc import AfcService
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "pymobiledevice3\services\afc.py", line 18, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "cmd2\__init__.py", line 53, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "cmd2\cmd2.py", line 125, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "cmd2\rl_utils.py", line 73, in <module>
AttributeError: 'NoneType' object has no attribute 'isatty'
```

I'm using `Python 3.10.4`, `cmd2 2.4.3`, and Windows 11.

**Comment by Starwarsfan2099** [comment]
@doronz88 Whoops, I missed removing an import. Apologies. Fixed with d3cda61acf4759ce1ed19e8a260cd444f5f15b1f.

**Comment by matan1008** [comment]
Sounds like your problem is here https://github.com/python-cmd2/cmd2/blob/master/cmd2/rl_utils.py#L73 (they should make sure stdout is not None) , and you should open a PR to cmd2 instead.

**Comment by doronz88** [comment]
I agree.  An import statement shouldn't be expected to raise an error. They should treat this error when trying to verify if it's a tty

**Comment by Starwarsfan2099** [comment]
Okay, thank you for the advice! I will do that instead.

**Pull request closed without merging**
