### PR TITLE
posix_util: fix `get_homedir()` (#1022)

### LINKED ISSUE #1022: pmd3 creates a new "~" directory in the working path
**Test environment**
- Manjaro KDE, Manjaro XFCE, Windows 11
- any idevice

**Describe the bug**
On execution, a new directory "~" is created (e.g by calling "usbmux list". Sometimes it also contains a subdirectory named "pymobiledevice3"

**To Reproduce**
1. Update to latest version
2. execute a pmd3 command aside from "version"

**Expected behavior**
Don't create new directorys.

**Additional context**
Might be related to the "get_home_folder()" fix 

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

### PR DESCRIPTION
**Pull request by doronz88**
Close #1022

### CODE REVIEW

**Comment by prosch88** [comment]
still a "~" gets created

**Comment by doronz88** [comment]
Did u install the PR branch?

**Comment by doronz88** [comment]
okay i verified it myself and this indeed solves. u didn't test the requested PR

**Comment by prosch88** [comment]
I did test the PR. On my system a folder still gets created
Weird. Now it seems fixed. Did an pip upgrade also ...

**Pull request merged**
