### PR TITLE
Bugfix/lockdown broken pipe

### PR DESCRIPTION
**Pull request by doronz88**

### CODE REVIEW

**Comment by vToMy** [comment]
2 issues:
* you added `@reconnect_on_remote_close` decorator on `validate_pairing` which is also being called by the decorator itself which could lead to infinite recursion.
* pretty sure the decorator won't work on `async def aio_start_service` since it's async.

**Comment by doronz88** [comment]
@vToMy your'e right. that's actually just a draft - still working on it.

**Comment by doronz88** [comment]
@vToMy the PR is now complete. You are welcome to review 🙂.
BTW, do you know if/how can I mark a PR as draft **after** it was published?

**Comment by vToMy** [comment]
Looking good now (and no idea...)

**Pull request merged**
