### PR TITLE
Allow include_escrow_bag to be True or False

### PR DESCRIPTION
**Pull request by KlutchKyle**

### CODE REVIEW

**Comment by doronz88** [comment]
when is `include_escrow_bag=False` desired?

**Comment by KlutchKyle** [comment]
> when is `include_escrow_bag=False` desired?

[TrollRestore](https://github.com/JJTech0130/TrollRestore)

I could only get TrollRestore to work with include_escrow_bag=False. Otherwise, it throws KeyError EscrowBag since create_using_usbmux() doesn't always include Escrow. see `perform_restore` in `__init__.py`

**Comment by doronz88** [comment]
Does re-pairing work? This sounds more like a bug that the original pair record didn't contain it

**Comment by doronz88** [comment]
I'm closing this. feel free to reopen if u intend on discussing the issue

**Pull request closed without merging**
